In [1]:
import numpy as np
from numpy import linalg as la

In [3]:

A = np.array([[0,1],[1,0]])
P = np.array([[-1,1],[1,1]])
#D es la diagonal
D= la.inv(P)@A@P

print(D)

[[-1.  0.]
 [ 0.  1.]]


In [8]:
# autovalores, autovectores = la.eig()
autoval, autovec= la.eig(A)

print(autoval,'\n', autovec)

[ 1. -1.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [9]:
print(la.inv(P))

[[-0.5  0.5]
 [ 0.5  0.5]]


In [10]:
A = np.array([[1,0,0,0,2],[0,0,3,0,0],[0,0,0,0,0],[0,2,0,0,0]])
print(A)

[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]]


In [12]:
V = A.T@A
U = A@A.T

In [15]:
val, vec = la.eig(V)
print(val)

val, vec = la.eig(U)
print(val)

[0. 5. 4. 9. 0.]
[5. 9. 0. 4.]


In [20]:
U, S, V = la.svd(A, full_matrices=False)
print( U, '\n')
#Raices de los sigma que son los valores propos de U y V
print( S, '\n')
print( V, '\n')

S= np.diag(S)

#construir matriz A
print(U@S@V)

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]] 

[3.         2.23606798 2.         0.        ] 

[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.         -1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]] 

[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]


In [28]:
#Realizamos la  suma para diferentes valores de K
print(S)
# k=1
print(S[0,0]*U[:,0:1]@V[0:1,:])
#k=2
print(S[0,0]*U[:,0:1]@V[0:1,:]+S[1,1]*U[:,1:2]@V[1:2,:])
#K=3
print(S[0,0]*U[:,0:1]@V[0:1,:]+S[1,1]*U[:,1:2]@V[1:2,:]+S[2,2]*U[:,2:3]@V[2:3,:])


[[3.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.        ]
 [0.         0.         2.         0.        ]
 [0.         0.         0.         0.        ]]
[[0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]
