In [2]:
import numpy as np
from numpy import linalg as la
u=np.array([[1,0,1]]) #dobre corchete para que sea una matriz y no una lista
v=np.array([[1],[2],[3]])


print("u = " ,u,'\n')
print('v = ',v)

u =  [[1 0 1]] 

v =  [[1]
 [2]
 [3]]


In [35]:
#se multiplican filas por columnas
print(np.sum(u*v.T), '\n')
print(u@v)

4 

[[4]]


In [4]:
print('la distancia entre u y v es', np.sqrt((u-v.T)@(u.T-v)))
print('la distancia entre u y v es', la.norm(u-v.T))



la distancia entre u y v es [[2.82842712]]
la distancia entre u y v es 2.8284271247461903


In [5]:
#calcular el coseno del ángulo que forman u y v
(np.sum(u*v.T))/(la.norm(u-v.T))

1.414213562373095

In [6]:
u/la.norm(u)@v/la.norm(v)

array([[0.75592895]])

In [7]:
import pandas as pd
vuelos = pd.read_csv("vuelos.csv")

In [8]:
vuelos.head()

MAD-AGP  MAD-LPA  MAD-SVQ  MAD-VLC  MAD-IBZ  MAD-SCQ
0      0.0      0.0      1.0      0.0      0.0      2.0
1      0.0      2.0      1.0      1.0      0.0      0.0
2      0.0      0.0      1.0      1.0      1.0      1.0
3      0.0      0.0      1.0      2.0      0.0      0.0
4      0.0      0.0      1.0      1.0      0.0      0.0

In [9]:
V=vuelos.to_numpy()

In [10]:
print(V)

[[0. 0. 1. 0. 0. 2.]
 [0. 2. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 2. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 2. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 2.]
 [1. 2. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]


In [11]:
# para mantener la estructura de submatriz, tienes que poner en el array [:,X:Y] siendo x la columna que quieres sacar y siendo Y = X+1 para que acabe hay
v6 = V[:,5:6]
print(v6)

[[2.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]]


In [12]:
v1 = V[:,0:1]
print(v1)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]]


In [13]:
v2 = V[:,1:2]
print(v2)

[[0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [2.]
 [0.]]


In [14]:
v4=V[:,3:4]
print(v4)

[[0.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]]


In [15]:
v5 = V[:,4:5]
print(v5)

[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]


In [16]:
sim61 = v6.T/la.norm(v6)@v1/la.norm(v1)
print(sim61)

[[0.33333333]]


In [17]:
sim62 = v6.T/la.norm(v6)@v2/la.norm(v2)
print(sim62)

[[0.38490018]]


In [18]:
sim64 = v6.T/la.norm(v6)@v4/la.norm(v4)
print(sim64)

[[0.38490018]]


In [19]:
sim65 = v6.T/la.norm(v6)@v5/la.norm(v5)
print(sim65)

[[0.20412415]]


In [20]:
v3=V[:,2:3]
print(v3)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [0.]
 [0.]
 [0.]
 [1.]]


In [21]:
sim31 = v3.T/la.norm(v3)@v1/la.norm(v1)
sim32 = v3.T/la.norm(v3)@v2/la.norm(v2)
sim34 = v3.T/la.norm(v3)@v4/la.norm(v4)
sim35 = v3.T/la.norm(v3)@v5/la.norm(v5)
print(sim31,"\n", sim32,"\n",sim34,"\n",sim35 )

[[0.18257419]] 
 [[0.21081851]] 
 [[0.52704628]] 
 [[0.4472136]]


In [22]:
print(la.norm(V,axis=0))

[1.73205081 3.         3.16227766 3.         1.41421356 3.46410162]


In [32]:
# MATRIZ Normalizada, cada columna a sido dividida por su norma gracias a phyton
#print(V/la.norm(V,axis=0))
VN=V/la.norm(V,axis=0)

S = VN.T@VN
print(S, '\n')
recomnedacion1 = V[0:1,:]@S

print(recomnedacion1)


[[1.         0.38490018 0.18257419 0.19245009 0.40824829 0.33333333]
 [0.38490018 1.         0.21081851 0.33333333 0.         0.38490018]
 [0.18257419 0.21081851 1.         0.52704628 0.4472136  0.45643546]
 [0.19245009 0.33333333 0.52704628 1.         0.23570226 0.38490018]
 [0.40824829 0.         0.4472136  0.23570226 1.         0.20412415]
 [0.33333333 0.38490018 0.45643546 0.38490018 0.20412415 1.        ]] 

[[0.84924085 0.98061887 1.91287093 1.29684664 0.85546189 2.45643546]]


In [34]:
#para que no se recomiende el mismo vuelo
recomnedacion1[V[0:1,:]!=0]=0
print(recomnedacion1)
print(np.argmax(recomnedacion1))

[[0.84924085 0.98061887 0.         1.29684664 0.85546189 0.        ]]
3


In [36]:
V@S
#MAtriz de recomendación por usuarios

array([[0.84924085, 0.98061887, 1.91287093, 1.29684664, 0.85546189,
        2.45643546],
       [1.14482463, 2.54415184, 1.9486833 , 2.19371294, 0.68291586,
        1.611136  ],
       [1.1166059 , 0.92905202, 2.43069534, 2.14764872, 1.88704   ,
        2.04545979],
       [0.56747437, 0.87748518, 2.05409255, 2.52704628, 0.91861812,
        1.22623582],
       [0.37502428, 0.54415184, 1.52704628, 1.52704628, 0.68291586,
        0.84133564],
       [0.69848171, 0.8065372 , 2.45643546, 1.43899273, 1.09855134,
        1.91287093],
       [1.52578342, 1.10313369, 1.16605593, 1.57735027, 0.8480747 ,
        1.71823351],
       [1.24401694, 2.10313369, 1.65073572, 2.10313369, 0.64395055,
        2.76980036],
       [2.10313369, 2.76980036, 1.06064667, 1.24401694, 0.61237244,
        2.10313369],
       [1.59082248, 0.59571869, 1.62978778, 0.95519863, 1.85546189,
        0.99389294]])