In [3]:
import pandas as pd
import numpy as np


pelis = pd.read_csv('ratings_example.csv')
pelis

userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [45]:
pelis_pivoted = pelis.pivot(index='userId',columns='movieId',values='rating').fillna(0)
pelis_pivoted


movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     4.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
667         0.0     0.0     0.0     0.0     0.0     4.0     0.0     0.0   
668         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
669         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
670         4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
671         5.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  161084  161155  161594  161830  161918  161944  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
667         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
668         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
669         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
670         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
671         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  162376  162542  162672  163949  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...  
667         0.0     0.0     0.0     0.0  
668         0.0     0.0     0.0     0.0  
669         0.0     0.0     0.0     0.0  
670         0.0     0.0     0.0     0.0  
671         0.0     0.0     0.0     0.0  

[671 rows x 9066 columns]

In [20]:
M = pelis_pivoted.to_numpy()
print(M,'\n', M.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]] 
 (671, 9066)


In [23]:
#Vamos a analizar usuarios porque son muchos menos que películas

from numpy import linalg as la
#Usuarios normalizados por filas MN
MN= (M.T/la.norm(M.T,axis=0)).T
print(MN)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.17996851 0.         0.         ... 0.         0.         0.        ]
 [0.11684125 0.         0.         ... 0.         0.         0.        ]]


In [25]:
#Matriz de similitud entre usuarios
S=MN@MN.T
print(S)

[[1.         0.         0.         ... 0.06291708 0.         0.01746565]
 [0.         1.         0.12429498 ... 0.02413984 0.17059464 0.1131753 ]
 [0.         0.12429498 1.         ... 0.08098382 0.13660585 0.17019275]
 ...
 [0.06291708 0.02413984 0.08098382 ... 1.         0.04260878 0.08520194]
 [0.         0.17059464 0.13660585 ... 0.04260878 1.         0.22867673]
 [0.01746565 0.1131753  0.17019275 ... 0.08520194 0.22867673 1.        ]]


In [29]:
#recomendación para el usuario 1
print(S[0:1,:]@M)
rounded_result = np.round(S[0:1,:] @ M, 3)
print(rounded_result)


[[20.87571921  8.46503375  4.44940719 ...  0.10949069  0.06569442
   0.28836607]]
[[20.876  8.465  4.449 ...  0.109  0.066  0.288]]


In [48]:
# función con el que le dices el usuario y coger el vectro y obtener el vector de recomendación
def recomendacion(usuario):
    x= np.round(S[usuario-1:usuario,:] @ M, 3)
    x[M[usuario-1:usuario,:]!=0] = 0
    return pelis_pivoted.columns[x.argmax()]

In [50]:
recomendacion(586)

1198