In [43]:
text = "A barber is a person. a barber is good person. a barber is huge person."

In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
import numpy as np

In [44]:
t = Tokenizer()
t.fit_on_texts([text])
print(t.word_index) # Print the encoding result of each word

{'a': 1, 'barber': 2, 'is': 3, 'person': 4, 'good': 5, 'huge': 6}


In [45]:
encoded=t.texts_to_sequences([text])
print(encoded)

[[1, 2, 3, 1, 4, 1, 2, 3, 5, 4, 1, 2, 3, 6, 4]]


In [46]:
one_hot = to_categorical(encoded)
print(one_hot)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0. 0.]]]
